### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by pearofducks** [vuejs/vue-syntax-highlight#142]
Looks like the newest changes are using the `YAMLMacros` package?

On MacOS 10.13.4 and Sublime 3175 (and 3.3.0 of this package).

When installing or restarting:

```
reloading plugin Vue Syntax Highlight.macros
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 116, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1183, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "/Users/pear/Library/Application Support/Sublime Text 3/Installed Packages/Vue Syntax Highlight.sublime-package/macros.py", line 1, in <module>
ImportError: No module named 'YAMLMacros'
```

**Comment by skyronic** [comment]
Hey @pearofducks thanks for reporting. Does the extension still work ok though.

@Thom1729 what's the best way to fix this?

**Comment by pearofducks** [comment]
@skyronic - nope, the extension fails to load! :)

**Comment by Thom1729** [comment]
My bad! The new PR should fix this.

The problem was that the `macros.py` file was in the package root where Sublime would try to execute it. This is completely unnecessary, because the macros are only used when someone builds the syntax. I've moved the macros file into a subdirectory where Sublime won't look for it. This should completely resolve the problem.

**Comment by pearofducks** [comment]
@Thom1729 @skyronic 

Confirmed working now against #143
